FROM alpine:latest AS builder
# FROM cgr.dev/chainguard/go as builder

# Install build dependencies
RUN apk update && apk add --no-cache --update-cache build-base openssl-dev libarchive-dev go

# Set the working directory
WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download the Go module dependencies
RUN go mod download

# Copy the rest of the application source code
COPY . .