FROM golang:1.23.3-alpine3.20

# Install build dependencies
RUN apk update && apk add --no-cache --update-cache build-base openssl-dev libarchive-dev

# Set the working directory
WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download the Go module dependencies
RUN go mod download

# Copy the rest of the application source code
COPY . .